Document: vchanger
Title: Debian vchanger Manual
Author: <insert document author here>
Abstract: This manual describes what vchanger is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vchanger/vchanger.sgml.gz

Format: postscript
Files: /usr/share/doc/vchanger/vchanger.ps.gz

Format: text
Files: /usr/share/doc/vchanger/vchanger.text.gz

Format: HTML
Index: /usr/share/doc/vchanger/html/index.html
Files: /usr/share/doc/vchanger/html/*.html
